name: sample

on:
  push:

env:
  MY_ENV: prd

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bar="baaaaaaaaa"
          if [[ "${{ env.MY_ENV }}" =~ ^(dev|stg)$ ]]; then
            bar="${{ env.MY_ENV }}/${bar}"
          fi
          echo "bar: $bar"
