name: sample

on:
  push:

env:
  MY_ENV: dev

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
        jq -c '.[]' <<< '${{ toJSON({"hoge":"hoge_string","bar":"bar_string"}) }}' | while read -r path; do
          hoge=$(echo $path | jq -r '.hoge')
          bar=$(echo $path | jq -r '.bar')
          if [[ "${{ env.MY_ENV }}" =~ ^(dev|stg))$ ]]; then
            bar="${{ inputs.env }}/${bar}"
          fi
          echo "hoge: $hoge, bar: $bar"
        done
